services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: host
    restart: always
    volumes:
      - ollama_storage:/root/.ollama

  lightrag:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: lightrag
    network_mode: host
    restart: always
    volumes:
      - /home/user/lightrag/inputs:/app/inputs
      - /home/user/lightrag/outputs:/app/outputs
      - /home/user/lightrag/dict:/app/dict

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    container_name: open-webui
    restart: always
    network_mode: host
    volumes:
      - open-webui-data:/app/backend/data

  apps-hub:
    build:
      context: /home/user/telegram-apps
      dockerfile: Dockerfile
    container_name: apps-hub
    restart: always
    network_mode: host
    depends_on:
      - ollama
    volumes:
      - /home/user/telegram-apps:/app

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  ollama_storage:
  open-webui-data:
  sd-data:
  portainer_data:
